airflow:
  image:
    repository: apache/airflow
    tag: 2.5.1
  executor: LocalExecutor
  config:
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  persistence:
    logs:
      enabled: true
      size: 1Gi
    dags:
      enabled: true
      size: 1Gi
  ingress:
    enabled: true
    host: airflow.local
    path: /
  secrets:
    sql_alchemy_conn:
      name: airflow-secrets
      key: sql_alchemy_conn
